Localization - Update Japanese (VD Notify)
DomT602/Doms-Arma-3-Mods pull request #15
Opened 2024-11-20 16:48 UTC by Apricot-ale

**When merged this pull request will:**
- _Update Japanese localization/translation_

2024-11-20 18:04 UTC, DomT602 requested changes

2024-11-20 18:04 UTC, DomT602 commented on DTVD/stringtable.xml
> +            <Japanese>描画距離が変更されました: 1%m (ホットキー %2)</Japanese>
I think the 1% is the wrong way around, it should be %1 - imagine the translation went a bit wonky!

2024-11-20 18:04 UTC, DomT602 commented on DTVD/stringtable.xml
> +            <Japanese>描画距離が変更されました: 1%m (%2%3m)</Japanese>
Again here

2024-11-20 23:14 UTC, Apricot-ale commented
What an embarrassing mistake! Thanks, I've fixed it.

2024-11-21 10:10 UTC, DomT602 approved these changes

2024-11-21 10:10 UTC, merged